# Generated by Django 4.2.14 on 2024-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_varified_certification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notactive', 'Not Active')]),
        ),
    ]
