# Generated by Django 4.2.14 on 2024-07-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_certification_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercertification',
            unique_together={('user', 'certification')},
        ),
    ]
