# Generated by Django 4.2.14 on 2024-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usercertification_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=4),
        ),
    ]
