# Generated by Django 4.2.14 on 2024-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_quiz_details_quiz_difficulty_quiz_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_option',
            field=models.TextField(default=''),
        ),
    ]
