# Generated by Django 4.2.14 on 2024-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(default='notattempted'),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('user', 'certification')},
        ),
    ]
