# Generated by Django 4.2.14 on 2024-08-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_quiz_status_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set(),
        ),
    ]
