# Generated by Django 4.2.14 on 2024-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
