# Generated by Django 4.2.14 on 2024-08-08 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_quiz_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercertification',
            old_name='marks_obt',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='usercertification',
            name='status',
        ),
        migrations.AddField(
            model_name='usercertification',
            name='certificate',
            field=models.ImageField(null=True, upload_to='certificates'),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='completion_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
