# Generated by Django 4.2.14 on 2024-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_marks_obt_usercertification_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertification',
            name='certificate',
            field=models.ImageField(null=True, upload_to='certificates/'),
        ),
    ]
