# Generated by Django 4.2.14 on 2024-08-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usercertification_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertification',
            name='score',
        ),
    ]
