# Generated by Django 4.2.14 on 2024-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_usercertification_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='marks_obt',
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(null=True, upload_to='certification/'),
        ),
    ]
